"""initial

Revision ID: fb10292ec730
Revises: 
Create Date: 2026-05-11 19:20:25.017923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb10292ec730'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('enumerator', 'founder', 'investor', 'admin', 'user', 'vendor', name='userrole'), nullable=False),
    sa.Column('wallet_address', sa.String(length=44), nullable=True),
    sa.Column('is_diaspora', sa.Integer(), nullable=True),
    sa.Column('origin_country', sa.String(length=100), nullable=True),
    sa.Column('residence_country', sa.String(length=100), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('university', sa.String(length=255), nullable=True),
    sa.Column('verified_on_chain', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('auth_provider', sa.String(length=20), nullable=False),
    sa.Column('provider_id', sa.String(length=255), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_provider_id'), 'users', ['provider_id'], unique=False)
    op.create_index(op.f('ix_users_wallet_address'), 'users', ['wallet_address'], unique=True)
    op.create_table('attestations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('wallet_address', sa.String(length=44), nullable=False),
    sa.Column('attestation_id', sa.String(length=255), nullable=False),
    sa.Column('issuer', sa.String(length=50), nullable=False),
    sa.Column('schema', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('on_chain', sa.Boolean(), nullable=True),
    sa.Column('sas_attestation_id', sa.String(length=255), nullable=True),
    sa.Column('transaction_signature', sa.String(length=255), nullable=True),
    sa.Column('cluster', sa.String(length=20), nullable=True),
    sa.Column('account_address', sa.String(length=44), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attestations_attestation_id'), 'attestations', ['attestation_id'], unique=True)
    op.create_index(op.f('ix_attestations_id'), 'attestations', ['id'], unique=False)
    op.create_index(op.f('ix_attestations_transaction_signature'), 'attestations', ['transaction_signature'], unique=False)
    op.create_index(op.f('ix_attestations_user_id'), 'attestations', ['user_id'], unique=False)
    op.create_index(op.f('ix_attestations_wallet_address'), 'attestations', ['wallet_address'], unique=False)
    op.create_table('credentials',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('EDUCATION', 'EMPLOYMENT', 'SKILL', 'CERTIFICATION', 'STARTUP_ROLE', name='credentialtype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('organization', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.Enum('USER_INPUT', 'SYSTEM_GENERATED', 'THIRD_PARTY', name='credentialsource'), nullable=True),
    sa.Column('verification_status', sa.Enum('UNVERIFIED', 'SUBMITTED', 'VERIFIED', 'REJECTED', name='verificationstatus'), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credentials_created_at'), 'credentials', ['created_at'], unique=False)
    op.create_index(op.f('ix_credentials_type'), 'credentials', ['type'], unique=False)
    op.create_index(op.f('ix_credentials_user_id'), 'credentials', ['user_id'], unique=False)
    op.create_index(op.f('ix_credentials_verification_status'), 'credentials', ['verification_status'], unique=False)
    op.create_table('ground_agent_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='applicationstatus'), nullable=True),
    sa.Column('experience', sa.String(length=1000), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('motivation', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ground_agent_applications_id'), 'ground_agent_applications', ['id'], unique=False)
    op.create_table('startups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('founder_id', sa.Integer(), nullable=False),
    sa.Column('startup_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('employees_verified', sa.Integer(), nullable=True),
    sa.Column('credibility_score', sa.Float(), nullable=True),
    sa.Column('transaction_signature', sa.String(length=88), nullable=True),
    sa.Column('funding_goal', sa.Float(), nullable=True),
    sa.Column('pitch_deck_url', sa.String(length=500), nullable=True),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('year_founded', sa.Integer(), nullable=True),
    sa.Column('team_size', sa.Integer(), nullable=True),
    sa.Column('mission', sa.String(length=1000), nullable=True),
    sa.Column('vision', sa.String(length=1000), nullable=True),
    sa.Column('products_services', sa.String(length=2000), nullable=True),
    sa.Column('business_registration_verified', sa.Boolean(), nullable=True),
    sa.Column('tax_id_verified', sa.Boolean(), nullable=True),
    sa.Column('documents_url', sa.String(length=500), nullable=True),
    sa.Column('founder_profile_verified', sa.Boolean(), nullable=True),
    sa.Column('founder_experience_years', sa.Integer(), nullable=True),
    sa.Column('founder_background', sa.Text(), nullable=True),
    sa.Column('has_mvp', sa.Boolean(), nullable=True),
    sa.Column('user_base_count', sa.Integer(), nullable=True),
    sa.Column('monthly_revenue', sa.Float(), nullable=True),
    sa.Column('milestones_completed', sa.Integer(), nullable=True),
    sa.Column('last_milestone_date', sa.DateTime(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('verification_summary', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['founder_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_startups_id'), 'startups', ['id'], unique=False)
    op.create_index(op.f('ix_startups_startup_id'), 'startups', ['startup_id'], unique=True)
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investor_id', sa.Integer(), nullable=False),
    sa.Column('startup_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['investor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)
    op.create_table('credential_hashes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('credential_id', sa.String(length=36), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('chain', sa.String(length=20), nullable=True),
    sa.Column('tx_signature', sa.String(length=88), nullable=True),
    sa.Column('block_number', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['credential_id'], ['credentials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credential_hashes_credential_id'), 'credential_hashes', ['credential_id'], unique=False)
    op.create_index(op.f('ix_credential_hashes_hash'), 'credential_hashes', ['hash'], unique=False)
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('startup_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('wallet_address', sa.String(length=88), nullable=True),
    sa.Column('certificate_id', sa.String(length=100), nullable=True),
    sa.Column('verified_on_chain', sa.Boolean(), nullable=True),
    sa.Column('transaction_signature', sa.String(length=88), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    op.create_table('proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('startup_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('funding_goal', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_ADMIN', 'LOCKED', 'REJECTED', name='proposalstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposals_id'), 'proposals', ['id'], unique=False)
    op.create_table('trust_signals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('credential_id', sa.String(length=36), nullable=True),
    sa.Column('signal_type', sa.Enum('VERIFIED_DEGREE', 'VERIFIED_EMPLOYMENT', 'FOUNDER_VERIFIED', 'INVESTOR_ACTIVITY', 'STARTUP_ROLE_VERIFIED', name='trustsignaltype'), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['credential_id'], ['credentials.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trust_signals_created_at'), 'trust_signals', ['created_at'], unique=False)
    op.create_index(op.f('ix_trust_signals_credential_id'), 'trust_signals', ['credential_id'], unique=False)
    op.create_index(op.f('ix_trust_signals_signal_type'), 'trust_signals', ['signal_type'], unique=False)
    op.create_index(op.f('ix_trust_signals_user_id'), 'trust_signals', ['user_id'], unique=False)
    op.create_table('investments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investor_id', sa.Integer(), nullable=False),
    sa.Column('proposal_version_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('escrow_pda_address', sa.String(length=88), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['investor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['proposal_version_id'], ['proposals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investments_id'), 'investments', ['id'], unique=False)
    op.create_table('milestones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposal_version_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'AGENT_VERIFIED', 'ADMIN_VERIFIED', 'PAID', name='milestonestatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['proposal_version_id'], ['proposals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_milestones_id'), 'milestones', ['id'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('milestone_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('DOCUMENT', 'MEDIA', 'DATA_LINK', 'SOCIAL_PROOF', name='evidencetype'), nullable=False),
    sa.Column('source', sa.Enum('STARTUP', 'SAAS_LAYER', 'THIRD_PARTY', name='evidencesource'), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('geotag', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_id'), 'evidence', ['id'], unique=False)
    op.create_table('ground_agent_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('milestone_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('evidence_url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('SUBMITTED', 'APPROVED', 'REJECTED', name='reportstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ground_agent_reports_id'), 'ground_agent_reports', ['id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('milestone_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_ground_agent_reports_id'), table_name='ground_agent_reports')
    op.drop_table('ground_agent_reports')
    op.drop_index(op.f('ix_evidence_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_milestones_id'), table_name='milestones')
    op.drop_table('milestones')
    op.drop_index(op.f('ix_investments_id'), table_name='investments')
    op.drop_table('investments')
    op.drop_index(op.f('ix_trust_signals_user_id'), table_name='trust_signals')
    op.drop_index(op.f('ix_trust_signals_signal_type'), table_name='trust_signals')
    op.drop_index(op.f('ix_trust_signals_credential_id'), table_name='trust_signals')
    op.drop_index(op.f('ix_trust_signals_created_at'), table_name='trust_signals')
    op.drop_table('trust_signals')
    op.drop_index(op.f('ix_proposals_id'), table_name='proposals')
    op.drop_table('proposals')
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_credential_hashes_hash'), table_name='credential_hashes')
    op.drop_index(op.f('ix_credential_hashes_credential_id'), table_name='credential_hashes')
    op.drop_table('credential_hashes')
    op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_startups_startup_id'), table_name='startups')
    op.drop_index(op.f('ix_startups_id'), table_name='startups')
    op.drop_table('startups')
    op.drop_index(op.f('ix_ground_agent_applications_id'), table_name='ground_agent_applications')
    op.drop_table('ground_agent_applications')
    op.drop_index(op.f('ix_credentials_verification_status'), table_name='credentials')
    op.drop_index(op.f('ix_credentials_user_id'), table_name='credentials')
    op.drop_index(op.f('ix_credentials_type'), table_name='credentials')
    op.drop_index(op.f('ix_credentials_created_at'), table_name='credentials')
    op.drop_table('credentials')
    op.drop_index(op.f('ix_attestations_wallet_address'), table_name='attestations')
    op.drop_index(op.f('ix_attestations_user_id'), table_name='attestations')
    op.drop_index(op.f('ix_attestations_transaction_signature'), table_name='attestations')
    op.drop_index(op.f('ix_attestations_id'), table_name='attestations')
    op.drop_index(op.f('ix_attestations_attestation_id'), table_name='attestations')
    op.drop_table('attestations')
    op.drop_index(op.f('ix_users_wallet_address'), table_name='users')
    op.drop_index(op.f('ix_users_provider_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###

