[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
certificate_registry = "D7SYneSxju3iTtJW9HPQMVjQRXgTCZi2vR2UWRk8nTRa"
investment_ledger = "FEQJZDk4afcXbSrRj7iW3PieNtrmeT2Hjtt5BCmoNfRr"
milestone_escrow = "c9ieYuJCWPuj1uhEN4VzNSQj68GHN1qw6tNvmsb7Eed"
startup_registry = "7caediXMm5C4vNg2yLD9rD176x7kAS7JBU3d2zigKFvw"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npm test"

[hooks]
