[workspace]
members = [
    "programs/startup-registry",
    "programs/milestone-escrow",
]
resolver = "1"

[patch.crates-io]
toml_edit = { package = "toml_edit", version = "=0.21.1" }

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1

[profile.release.build-override]
opt-level = 3
incremental = true
codegen-units = 1

