[workspace]
members = [
    "programs/startup-registry",
    "programs/milestone-escrow",
]
resolver = "1"

[patch.crates-io]
block-buffer = { path = "patches/utils/block-buffer" }
cpufeatures = { path = "patches/utils/cpufeatures" }
toml_edit = { path = "patches/toml/crates/toml_edit" }
getrandom = { git = "https://github.com/rust-random/getrandom", tag = "v0.2.15" }
crypto-common = { path = "patches/utils/traits/crypto-common" }
digest = { path = "patches/utils/traits/digest" }

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1

[profile.release.build-override]
opt-level = 3
incremental = true
codegen-units = 1

